apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Kubernetes resources to be managed by kustomize
resources:
  - api/
  - db/
  - cache/
  - kafka/
  
# Customizations that need to be made
commonLabels:
  company: KodeKloud
