version: '2'
services:
  web:
    image: fotonicia/nginx
    ports:
      - 8080:80
    volumes:
      - ./magento2:/var/www/html
    networks:
      appnet:
        ipv4_address: 10.5.0.6

  php:
    image: ziffity/zphp:latest
    volumes:
      - ./magento2:/var/www/html
    networks:
      appnet:
        ipv4_address: 10.5.0.5

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento2
      MYSQL_USER: magento2
      MYSQL_PASSWORD: magento2
    networks:
      appnet:
        ipv4_address: 10.5.0.3

volumes:
  db_data:
    driver: "local"

networks:
  appnet:
    driver: bridge
    ipam:
      config: 
        - 
          gateway: "10.5.0.1"
          subnet: 10.5.0.0/16
