apiVersion: v1
kind: Pod
metadata:
  name: test-pd2
spec:
  containers:
    - name: mysql
      image: mysql
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: "rootpasswd"
      volumeMounts:
      - mountPath: /var/lib/mysql
        name: site-data
        subPath: mysql
    - name: php
      image: php:7.0-apache
      volumeMounts:
      - mountPath: /var/www/html
        name: site-data
        subPath: html
  volumes:
  - name: site-data
    hostPath:
      # directory location on host (Must available) mkdir /data
      path: /data
      # this field is optional
      type: Directory