---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos
  labels:
    app: centos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: centos
  template:
    metadata:
      labels:
        app: centos
    spec:
      containers:
      - name: centos-container
        image: gcr.io/kodekloud/centos-ssh-enabled:node

---
apiVersion: v1
kind: Service
metadata:
  name: centos-svc
spec:
  type: NodePort
  selector:
    app: centos
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30012


