#Manage secrets in kubernetes cluster.
kubectl create secret generic ecommerce --from-file=/opt/ecommerce.txt

apiVersion: v1
kind: Pod
metadata:
  name: secret-devops
spec:
  containers:
  - name: secret-container-devops
    image: debian:latest
    command: ["/bin/bash"]
    args: ["-c", "sleep 10000"]
    volumeMounts:
    - name: secret-volume-devops
      mountPath: "/opt/games"
      readOnly: true
  volumes:
  - name: secret-volume-devops
    secret:
      secretName: ecommerce
