---
apiVersion: v1 
kind: PersistentVolume            
metadata:
  name: pv-nautilus
spec:
  storageClassName: manual      
  capacity:
    storage: 5Gi
  accessModes: 
    - ReadWriteOnce
  hostPath:                       
    path: "/mnt/dba"

---    
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:                          
  name: pvc-nautilus
spec:                              
  storageClassName: manual     
  accessModes:
  - ReadWriteOnce                
  resources:
    requests: 
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata: 
  name: pod-nautilus
  labels:
    app: web
spec:
  containers:
  - name: container-nautilus
    image: nginx:latest
    volumeMounts:
    - name: volume
      mountPath: /var/www/html
  volumes:
  - name: volume
    persistentVolumeClaim:
      claimName: pvc-nautilus

---
apiVersion: v1
kind: Service        
metadata:
  name: web-nautilus         
  labels:             
    app: web
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:    
    app: web