---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "eportal-script-engine.fullname" . }}-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    fsType: ext4
    pdName:

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "eportal-script-engine.fullname" . }}-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi