apiVersion: apps/v1
kind: Deployments
metadata:
  labels:
    run: httpd-frontend
  name: httpd-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      run: httpd-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: httpd-frontend
    spec:
      containers:
      - image: nginx
        name: nginx
    

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: httpd-frontend
  name: httpd-frontend
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: httpd-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: httpd-frontend
    spec:
      containers:
      - image: httpd:2.4-alpine
        imagePullPolicy: IfNotPresent
        name: httpd-frontend
