apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: mynx
  name: mynx
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: mynx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: mynx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: mynx
      nodeSelector:
        env: "prod"
