apiVersion: v1
kind: Service
metadata:
  labels:
    run: mynx
  name: mynx
  namespace: default 
spec:
  clusterIP: 10.96.93.121
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30005
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: mynx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
