apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2020-01-29T07:19:33Z"
  generation: 3
  labels:
    run: ziffity
  name: ziffity
  namespace: suren
  resourceVersion: "16469"
  selfLink: /apis/apps/v1/namespaces/default/deployments/ziffity
  uid: 13e048e3-094d-4745-9853-e7d16bc8e0a2
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: ziffity
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ziffity
    spec:
      containers:
      - image: nginx:1.15
        imagePullPolicy: IfNotPresent
        name: ziffity
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2020-01-29T07:19:38Z"
    lastUpdateTime: "2020-01-29T07:19:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-01-29T07:19:33Z"
    lastUpdateTime: "2020-01-29T07:22:05Z"
    message: ReplicaSet "ziffity-79494d56f8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
