apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Kubernetes resources to be managed by kustomize
resources:
  - api-deploy.yaml
  - api-service.yaml 
  
# Customizations that need to be made
commonLabels:
  company: KodeKloud