apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-test-pvc
  namespace: designer
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: "smb-test-pv"
  resources:
    requests:
      storage: 1Ti
  