apiVersion: v1
kind: Secret
metadata:
  name: suren-secret
  namespace: designer
type: Opaque
data:
  azurestorageaccountname: ZGVzaWduZXJmaWxlc2Vhc3R1czJkZXY=
  azurestorageaccountkey: cE1sSmNRcDhXVmQ1MG1RMWsrYWV4RUpWVElHTUNMOWZVZzlZSm5BSm1HQUg1ZFdEWXZsZGdsS29XUFd1cE0wN1N1WExVRXZBWG1iN0FzT0VkNStQaVE9PQ==

