name: Actions workflow

on: [push]

jobs:
  run-action-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: actions/checkout@main
        run: |
          pwd
          ls -a
      - name: After checkout listing files
        run: |
          pwd
          ls -a
      - name: Simple JS action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: Surendar
      - name: Logging the greet time
        run: echo "${{ steps.greet.outputs.time }}"