name: Try to execute shell commands using github actions.

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World !!"

      - name: Check the node & npm version (Multiline script)
        run: |
          node -v
          npm -v

      - name: Check the os version
        run: cat /etc/os-release