name: Try to execute shell commands using github actions.

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    needs: ["run-windows-command"]
    steps:
      - name: echo a string
        run: echo "Hello World !!"
      - name: dump
        run: |
          echo ${{ contains( 'Suren', 'ur' ) }}
          echo ${{ startswith( 'Suren', 'Su' ) }}
          echo ${{ endswith( 'Suren', 'en' ) }}
          echo ${{ format( 'Hello {0} {1} {2} {3}', 'Surendar', 'welcome', '!', '!' ) }}

      - name: Check the node & npm version (Multiline script)
        run: |
          node -v
          npm -v
          python -V

      - name: Check the os version
        run: cat /etc/os-release

      - name: Python commands
        run: |
          import platform
          print(platform.processor())
        shell: python
  
  run-windows-command:
    runs-on: windows-latest
    steps:
      - name: Directory Location
        run: Get-Location
      - name: Bash cmd in windows vm
        run: pwd
        shell: bash
